name: 'Render website'
description: 'Render dita-ot/docs into dita-ot/website'
inputs:
  WEBSITE_PLUGIN_BRANCH:
    description: 'Website plug-in ref'
    default: 'master'
  DITA_OT_VERSION:
    description: 'DITA-OT version used for rendering'
    default: '4.2.3'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: 'gradle'
    - name: Set Node.js version 12.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Download website plug-in
      shell: bash
      run: |
        curl -sL https://github.com/dita-ot/org.dita-ot.html/archive/refs/heads/${{ inputs.WEBSITE_PLUGIN_BRANCH }}.zip -o org.dita-ot.html.zip
    - name: Cache stable DITA-OT
      uses: actions/cache@v2
      with:
        path: dita-ot-${{ inputs.DITA_OT_VERSION }}
        key: ${{ runner.os }}-dita-ot-${{ inputs.DITA_OT_VERSION }}
    - name: Download stable DITA-OT
      shell: bash
      run: |
        if [ ! -d "dita-ot-${{ inputs.DITA_OT_VERSION }}" ]; then
          curl -sL https://github.com/dita-ot/dita-ot/releases/download/${{ inputs.DITA_OT_VERSION }}/dita-ot-${{ inputs.DITA_OT_VERSION }}.zip -o dita-ot-${{ inputs.DITA_OT_VERSION }}.zip
          unzip dita-ot-${{ inputs.DITA_OT_VERSION }}.zip
        else
          echo "Use cached dita-ot-${{ inputs.DITA_OT_VERSION }}"
        fi
        dita-ot-${{ inputs.DITA_OT_VERSION }}/bin/dita install org.dita-ot.html.zip --force -v
    - name: Get develop DITA-OT ETag
      shell: bash
      run: |
        curl -sI https://s3-eu-west-1.amazonaws.com/dita-ot/dita-ot-develop.zip | grep -F ETag | cut -d'"' -f 2 > dita-ot-develop.etag
    - name: Cache develop DITA-OT
      uses: actions/cache@v2
      with:
        path: dita-ot-develop
        key: ${{ runner.os }}-dita-ot-develop-${{ hashFiles('dita-ot-develop.etag') }}
        restore-keys: |
          ${{ runner.os }}-dita-ot-develop-
    - name: Download develop DITA-OT
      shell: bash
      run: |
        if [ ! -d "dita-ot-develop" ]; then
          curl -sL https://s3-eu-west-1.amazonaws.com/dita-ot/dita-ot-develop.zip -o dita-ot-develop.zip
          unzip dita-ot-develop.zip -d dita-ot-develop
        else
          echo "Use cached dita-ot-develop"
        fi
        echo "DITA_OT_DEV=$(find dita-ot-develop -name 'dita-ot-*@*' -type d | head -1)" >> $GITHUB_ENV
    - name: Run DITA-OT
      shell: bash
      run: |
        ./gradlew site \
          -PditaHome=${{ github.workspace }}/dita-ot-${{ inputs.DITA_OT_VERSION }} \
          -PoutputDir=${{ github.workspace }}/website/dev \
          -PditaHomeSrc=${{ env.DITA_OT_DEV }} \
          --info --stacktrace --no-daemon
